/**
    This class represents the projectiles generated by a player's gun.
    It handles the animation, movement, collision, and states of the projectile.
    
    @author Hiroki S. Watanabe (244844)
    @author Yuuki S. Watanabe (244845)
    @version 20 May 2025
    I have not discussed the Java language code in my program
    with anyone other than my instructor or the teaching assistants
    assigned to this course.
    I have not used Java language code obtained from another student,
    or any other unauthorized source, either modified or unmodified.
    If any Java language code or documentation used in my program
    was obtained from another source, such as a textbook or website,
    that has been clearly noted with a proper citation in the comments
    of my program.
 */

import java.awt.Graphics2D;

public class ProjectileBullet implements ObjectProjectile, SpriteGraphic {
    private ShapeDimensions hitbox;
    private ShapeDimensions spriteBounds;
    private Player shooter;
    private PlayerGun gun;
    private int gunID;
    private double gunWidth, handleWidth, bulletWidth, bulletHeight, gunRotation;
    private double barrelTipX, barrelTipY, bulletStartX, bulletStartY, bulletRotation, spread, currFrameShot, currFrameBullet, currFrameImpact;
    private boolean finished, shot, collided, hasShotEffect;
    private double[] speed;

    /**
     * Constructs a new ProjectileBullet object based on the shooter and the gun used.
     * Caches values used to calculate bullet position, trajectory, and dimensions.
     *
     * @param shooter The player who fired the bullet.
     * @param gun The gun that fired the bullet.
     * @param randomVar A random variable (0.0 to 1.0) to apply bullet spread.
     * @param hasShotEffect Whether the gun should display a muzzle flash effect.
     */
    public ProjectileBullet(Player shooter, PlayerGun gun, double randomVar, boolean hasShotEffect) {
        this.shooter = shooter;
        this.gun = gun;
        this.hasShotEffect = hasShotEffect;
        shot = true;
    
        gunID = gun.getCurrentGun();
        spread = gun.getGunStat(Const.SPREAD);
        bulletRotation = gun.getImage(Const.ROTATION) + Math.toRadians((randomVar - 0.5)*spread);
        
        gunRotation = gun.getImage(Const.ROTATION);
        gunWidth = gun.getImage(Const.WIDTH);
        handleWidth = gun.getGunStat(Const.HANDLE_WIDTH);
        bulletWidth = gun.getGunStat(Const.BULLET_WIDTH);
        bulletHeight = gun.getGunStat(Const.BULLET_HEIGHT);
    
        speed = new double[2];
        speed[Const.X] = gun.getGunStat(Const.BULLET_SPEED)*Math.cos(bulletRotation);
        speed[Const.Y] = gun.getGunStat(Const.BULLET_SPEED)*Math.sin(bulletRotation);
    
        barrelTipX = gun.getImage(Const.PIVOT_X) + (gunWidth - handleWidth/2)*Math.cos(gunRotation);
        barrelTipY = gun.getImage(Const.PIVOT_Y) + (gunWidth - handleWidth/2)*Math.sin(gunRotation);

        bulletStartX = barrelTipX - (bulletHeight/2)*Math.abs(Math.sin(gunRotation));
        bulletStartY = barrelTipY - (bulletHeight/2)*Math.abs(Math.cos(gunRotation));
    
        hitbox = new ShapeDimensions(
            bulletStartX, 
            bulletStartY, 
            bulletHeight, 
            bulletHeight
        );
        spriteBounds = new ShapeDimensions(
            hitbox.getX(), 
            hitbox.getY(), 
            bulletWidth, 
            bulletHeight
        );
        spriteBounds.setRotation(bulletRotation);
    }

    @Override
    public void draw(Graphics2D g2d, SpriteManager sd) {
        spriteBounds.setPivot(hitbox.getX() + hitbox.getWidth()/2, hitbox.getY() + hitbox.getWidth()/2); 

        if (collided) drawImpactEffect(g2d, sd);
        else if (!finished) drawBulletAnimation(g2d, sd);
        
        if (shot && hasShotEffect) drawShotEffect(g2d, sd);
    }

    /**
     * Draws the bullet's impact animation.
     *
     * @param g2d the Graphics2D object to draw on
     * @param sd the object used to retrieve and manage the sprites that will be used
     */
    private void drawImpactEffect(Graphics2D g2d, SpriteManager sd) {
        sd.drawAnimatedEffect(
            g2d, Const.IMPACT, 
            hitbox.getX() - 20 + hitbox.getWidth()/2, 
            hitbox.getY() - 20 + hitbox.getHeight()/2, 
            40, 40, 
            0, 0, 0,
            (int) currFrameImpact
        );
        currFrameImpact = (currFrameImpact + Const.ANIM_SPEED[Const.IMPACT]);
        if (currFrameImpact >= Const.ANIM_FRAMES[Const.IMPACT]) {
            currFrameImpact = 0;
            finished = true;
        }
    }

    /**
     * Draws the bullet's projectile animation.
     *
     * @param g2d the Graphics2D object to draw on
     * @param sd the object used to retrieve and manage the sprites that will be used
     */
    private void drawBulletAnimation(Graphics2D g2d, SpriteManager sd) {
        sd.drawAnimatedProjectile(g2d, Const.AMMO_ANIM[gunID], spriteBounds, (int) currFrameBullet);
        currFrameBullet = (currFrameBullet + Const.ANIM_SPEED[Const.AMMO_ANIM[gunID]]) % Const.ANIM_FRAMES[Const.AMMO_ANIM[gunID]];
    }

    /**
     * Draws the bullet's muzzle flash.
     *
     * @param g2d the Graphics2D object to draw on
     * @param sd the object used to retrieve and manage the sprites that will be used
     */
    private void drawShotEffect(Graphics2D g2d, SpriteManager sd) {
        sd.drawAnimatedEffect(
            g2d, Const.SHOT,
            barrelTipX, 
            barrelTipY - 21,
            42, 42,
            gun.getImage(Const.ROTATION),
            barrelTipX,
            barrelTipY,
            (int) currFrameShot
        );
        currFrameShot = (currFrameShot + Const.ANIM_SPEED[Const.SHOT]);
        if (currFrameShot >= Const.ANIM_FRAMES[Const.SHOT]) {
            currFrameShot = 0;
            shot = false;
        }
    }

    @Override
    public void updatePosition() {
        if (!collided) {   
            moveX(speed[Const.X]);
            moveY(speed[Const.Y]);
        }
    }

    /**
     * Detects if projectile is colliding with any object.
     * If object is an entity, projectile will damage and knockback entity.
     */
    @Override
    public void detectCollision(ObjectHitbox o) {
        double radius = getImage(Const.WIDTH)/2;
        double bulletX = getImage(Const.X) + getImage(Const.WIDTH)/2;
        double bulletY = getImage(Const.Y) + getImage(Const.HEIGHT)/2;

        double objectX = Math.clamp(bulletX, o.getHitbox(Const.X), o.getHitbox(Const.X) + o.getHitbox(Const.WIDTH));
        double objectY = Math.clamp(bulletY, o.getHitbox(Const.Y), o.getHitbox(Const.Y) + o.getHitbox(Const.HEIGHT));

        double differenceX = objectX - bulletX;
        double differenceY = objectY - bulletY;

        if ((Math.pow(differenceX, 2) + Math.pow(differenceY, 2)) < Math.pow(radius, 2)) {
            if (o instanceof ObjectEntity) {
                ((ObjectEntity) o).takeDamage(gun.getGunStat(Const.DAMAGE));
                ((ObjectEntity) o).takeKnockback(gun.getGunStat(Const.KNOCKBACK), spriteBounds.getRotation());
            }
            collided = true;
        }
    }

    @Override
    public boolean hasCollided() {
        return collided;
    }
    @Override
    public boolean hasFinished() {
        return finished;
    }
    @Override
    public ObjectEntity getShooter() {
        return shooter;
    }
    @Override
    public void moveX(double speed) {
        hitbox.setX(getHitbox(Const.X) + speed);
        spriteBounds.setX(getImage(Const.X) + speed);
    }
    @Override
    public void moveY(double speed) {
        hitbox.setY(getHitbox(Const.Y) + speed);
        spriteBounds.setY(getImage(Const.Y) + speed);
    }
    @Override
    public double getSpeed(int dimensionID) {
        return speed[dimensionID];
    }
    @Override
    public double getHitbox(int dimensionID) {
        switch (dimensionID) {
            case Const.X: return hitbox.getX();
            case Const.Y: return hitbox.getY();
            case Const.WIDTH: return hitbox.getWidth();
            case Const.HEIGHT: return hitbox.getHeight();
            default: return 0;
        }
    }
    @Override
    public double getImage(int dimensionID) {
        switch (dimensionID) {
            case Const.X: return spriteBounds.getX();
            case Const.Y: return spriteBounds.getY();
            case Const.WIDTH: return spriteBounds.getWidth();
            case Const.HEIGHT: return spriteBounds.getHeight();
            case Const.ROTATION: return spriteBounds.getRotation();
            case Const.PIVOT_X: return spriteBounds.getPivotX();
            case Const.PIVOT_Y: return spriteBounds.getPivotY();
            default: return 0;
        }
    }
    @Override
    public int getLayer() {
        return (int) (getHitbox(Const.Y));
    }
}
